-- MySQL Script generated by MySQL Workbench
-- 03/23/18 19:54:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `idempresa` INT NOT NULL,
  `nomefantasia` VARCHAR(200) NULL,
  `cnpj` VARCHAR(20) NULL,
  `flagativo` CHAR(1) NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`setor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`setor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`setor` (
  `idsetor` INT NOT NULL,
  `idempresa` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `flagativo` CHAR(1) NULL,
  PRIMARY KEY (`idsetor`, `idempresa`),
  INDEX `fk_setor_empresa1_idx` (`idempresa` ASC),
  CONSTRAINT `fk_setor_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `mydb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `idsetor` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `flagativo` CHAR(1) NULL,
  PRIMARY KEY (`idpessoa`),
  INDEX `fk_pessoa_setor1_idx` (`idsetor` ASC),
  CONSTRAINT `fk_pessoa_setor1`
    FOREIGN KEY (`idsetor`)
    REFERENCES `mydb`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `idempresa` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `flagativo` CHAR(1) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_pessoa1_idx` (`idpessoa` ASC),
  INDEX `fk_usuario_empresa1_idx` (`idempresa` ASC),
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `mydb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
